import turtle
turtle.penup()
turtle.fd(20)
turtle.pendown()
turtle.fd(150)
turtle.penup()
turtle.seth(90)
turtle.fd(20)
turtle.pendown()
turtle.fd(150)
turtle.penup()
turtle.fd(20)
turtle.seth(180)
turtle.fd(20)
turtle.pendown()  
turtle.fd(150)         
turtle.penup()
turtle.fd(20)
turtle.seth(270)
turtle.fd(20)
turtle.pendown()
turtle.fd(150)
turtle.penup()
turtle.fd(20)

