from turtle import*
edge=10
setup(500,500,200,200)
while edge <50:
    theta=90
    seth(theta)
    fd(edge)
    theta=theta+90
    seth(theta)
    fd(edge)
    edge=edge+5
    theta=theta+90
    seth(theta)
    fd(edge)
    theta=theta+90
    seth(theta)
    fd(edge)
    edge=edge+5
theta=90
seth(theta)
fd(edge)
theta=theta+90
seth(theta)
fd(edge)
edge=edge+5
theta=theta+90
seth(theta)
fd(edge)
theta=theta+90
seth(theta)
